# Role definitions: required skills, bonus skills, and minimum thresholds
# This is the source of truth for scoring and gap analysis

ROLES = [
    {
        "id": "backend",
        "title": "Backend Developer",
        "required_skills": ["Node.js", "Express", "Flask", "FastAPI", "Django", "Spring Boot"],
        "bonus_skills": ["Docker", "Redis", "PostgreSQL", "MongoDB", "System Design", "REST APIs", "GraphQL"],
        "languages": ["Python", "Java", "JavaScript", "TypeScript", "Go"],
        "cgpa_min": 6.5,
        "description": "Builds server-side logic, APIs, and databases.",
    },
    {
        "id": "fullstack",
        "title": "Full Stack Developer",
        "required_skills": ["React", "Node.js", "Express"],
        "bonus_skills": ["Next.js", "TypeScript", "PostgreSQL", "MongoDB", "Docker", "GraphQL", "REST APIs"],
        "languages": ["JavaScript", "TypeScript", "Python"],
        "cgpa_min": 6.5,
        "description": "Works across frontend and backend.",
    },
    {
        "id": "frontend",
        "title": "Frontend Developer",
        "required_skills": ["React", "JavaScript", "TypeScript"],
        "bonus_skills": ["Next.js", "Vue", "Angular", "CSS", "REST APIs", "GraphQL"],
        "languages": ["JavaScript", "TypeScript"],
        "cgpa_min": 6.0,
        "description": "Builds user interfaces and web experiences.",
    },
    {
        "id": "data_analyst",
        "title": "Data Analyst",
        "required_skills": ["Data Analysis", "SQL", "MySQL", "PostgreSQL"],
        "bonus_skills": ["Python", "Machine Learning", "Firebase"],
        "languages": ["Python", "R", "SQL"],
        "cgpa_min": 7.0,
        "description": "Analyzes data and generates business insights.",
    },
    {
        "id": "ml_engineer",
        "title": "ML Engineer",
        "required_skills": ["Machine Learning", "Deep Learning", "Python"],
        "bonus_skills": ["Data Analysis", "Docker", "AWS", "GCP", "PostgreSQL"],
        "languages": ["Python", "R"],
        "cgpa_min": 7.5,
        "description": "Builds and deploys machine learning models.",
    },
    {
        "id": "devops",
        "title": "DevOps Engineer",
        "required_skills": ["Docker", "CI/CD", "Linux"],
        "bonus_skills": ["Kubernetes", "AWS", "GCP", "Azure", "Git"],
        "languages": ["Python", "Go", "Bash"],
        "cgpa_min": 6.0,
        "description": "Manages infrastructure, pipelines, and deployments.",
    },
    {
        "id": "cloud",
        "title": "Cloud Engineer",
        "required_skills": ["AWS", "GCP", "Azure"],
        "bonus_skills": ["Docker", "Kubernetes", "CI/CD", "Linux", "Terraform"],
        "languages": ["Python", "Go"],
        "cgpa_min": 6.5,
        "description": "Designs and manages cloud infrastructure.",
    },
    {
        "id": "sde",
        "title": "Software Engineer (General)",
        "required_skills": ["DSA", "Git"],
        "bonus_skills": ["System Design", "REST APIs", "Docker", "PostgreSQL", "MongoDB"],
        "languages": ["Java", "Python", "C++", "JavaScript", "Go"],
        "cgpa_min": 6.5,
        "description": "General software engineering role across domains.",
    },
]